eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8761/eureka
      instance:
      preferIpAddress: true
spring:
   application:
      name: eureka-serviceRegister
      

      
logging:
  level:
    com.example.eurekaserviceRegister: DEBUG
 
